version: "3.7"
services:
  node:
    image: "node:17"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./api/:/home/node/app
    expose:
      - "8081"
    ports:
      - "8081:8081"
    command: "npm run vmdev"
  web:
    image: "httpd:latest"
    volumes:
      - "./public-frontend:/usr/local/apache2/htdocs/"
    expose:
      - "80"
    ports:
      - "8082:80"
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: testdb
      MYSQL_USER: testdb
      MYSQL_PASSWORD: testdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
