version: "3.7"
services:
  api:
    image: "node:17"
    container_name: botonews-api
    user: "node"
    container_name: botonews-api
    working_dir: /home/node/app
    links:
      - "db"
    env_file:
      - .env-db
      - .env-auth
    volumes:
      - ./api/:/home/node/app
    expose:
      - "8081"
    ports:
      - "8081:8081"
    command: "npm run vmdev"
  frontend:
    container_name: botonews-frontend
    image: "httpd:latest"
    container_name: botonews-web
    volumes:
      - "./public-frontend:/usr/local/apache2/htdocs/"
    expose:
      - "80"
    ports:
      - "8082:80"
  db:
    image: mysql
    container_name: botonews-db
    restart: unless-stopped
    env_file:
      - .env-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
  pma:
    image: phpmyadmin
    container_name: botonews-phpmyadmin
    restart: unless-stopped
    ports:
      - 8088:80
    links:
      - db