# Keep the contributors list updated in the README.md file

name: update-contributors

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-contributors"
  update-contributors:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: update the readme
        run: wget -O - https://raw.githubusercontent.com/epfl-dojo/contributeurs-trombinoscope/dev/ponsfrilus/update-contributors.sh | bash

      # Runs a set of commands using the runners shell
      - name: commit if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: "[auto] Update contributors"

          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          # commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: README.md

          # Optional commit user and author settings
          commit_user_name: ContributorsBot # defaults to "GitHub Actions"
